#!/bin/sh

usage()
{
	echo "  bond-ctrl [add|del] <bond-id> mode [manual|dynamic] <port-list>"
	echo "		<bond-id>  --- 1~3"
	echo "		mode:"
	echo "		      manual  -- xor"
	echo "		      dynamic -- lacp"
	echo "		<port-list>   -- p1,p2,p3,p4,p5 (etc. \"p1,p2\")"
	echo ""
	echo " example:"
	echo " 		Add a new bond1 with port 1 and port2 mode is lacp."
	echo " 		bond-ctrl add 1 mode dynamic p1,p2"
	echo ""
	echo " 		Delete bond1"
	echo " 		bond-ctrl del 1"
	echo ""

	exit 0
}

_del_bond()
{
	bid=$1
	[ ! -d /sys/devices/virtual/net/bond$bid ] && exit 1

	[ -e /var/run/bond-monitor$bid.pid ] && {
		start-stop-daemon -K -p /var/run/bond-monitor$bid.pid
	}

	ifconfig bond$bid down
	slave_list=`cat /sys/devices/virtual/net/bond$bid/bonding/slaves`
	for s in $slave_list
	do
		echo -$s > /sys/devices/virtual/net/bond$bid/bonding/slaves
	done
	echo -bond$bid > /sys/class/net/bonding_masters

	# remove bond from hardware
	ssdk_sh_id 0 trunk group set $bid disable 0x00 > /dev/null
}

_add_bond()
{
	bid=$1
	mode=$2
	port_list=$3
	
	[ $1 -lt 1 ] && usage
	[ $1 -gt 3 ] && usage

	case $mode in
	man*) ;;
	dyn*) ;;
	   *) usage;;
	esac
	
	if [ -d /sys/devices/virtual/net/bond$bid ]
	then
		echo "!! You should deleta bond $bid first!!"
		exit 0
	else
		echo +bond$bid > /sys/class/net/bonding_masters
	fi

	ifconfig bond$bid down

	case $mode in
	man*) echo balance-xor > /sys/devices/virtual/net/bond$bid/bonding/mode ;;
	dyn*) echo 802.3ad     > /sys/devices/virtual/net/bond$bid/bonding/mode ;;
	   *) usage;;
	esac

	echo 1000 > /sys/devices/virtual/net/bond$bid/bonding/miimon
	echo "layer2+3" > /sys/devices/virtual/net/bond$bid/bonding/xmit_hash_policy	
	
	curr_slave_list=`cat /sys/devices/virtual/net/bond$bid/bonding/slaves`
	port_list=`echo $port_list | sed "s/,/ /g"`
	for s in $port_list
	do
		p_existed=`echo $curr_slave_list | grep $s`
		if [ -z $p_existed ]
		then
			echo +$s > /sys/devices/virtual/net/bond$bid/bonding/slaves
		fi
	done

	ifconfig bond$bid up

	start-stop-daemon -b -S -q -m -p /var/run/bond-monitor$bid.pid -x /usr/sbin/bond-monitor -- $bid
}

[ $# -lt 1 ] && usage

case $1 in
add) _add_bond $2 $4 $5;;
del) _del_bond $2 ;;
  *) usage ;;
esac


