#ifndef __EARLY_INIT_LAYOUT_H__
#define __EARLY_INIT_LAYOUT_H__

#define EARLY_INIT_MAGIC_NUM                                0xAA

#define EARLY_INIT_SIZE                                     11

#define EARLY_INIT_MAGIC_NUM_OFFSET                         0

#define EARLY_INIT_DIMM_0_SPD_EEPROM_I2C_ADDR_OFFSET        1

#define EARLY_INIT_DIMM_0_SPD_OFFSET_IN_EEPROM_LSB_OFFSET   2

#define EARLY_INIT_DIMM_0_SPD_OFFSET_IN_EEPROM_MSB_OFFSET   3

#define EARLY_INIT_DIMM_1_SPD_EEPROM_I2C_ADDR_OFFSET        4

#define EARLY_INIT_DIMM_1_SPD_OFFSET_IN_EEPROM_LSB_OFFSET   5

#define EARLY_INIT_DIMM_1_SPD_OFFSET_IN_EEPROM_MSB_OFFSET   6

#endif
