#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org

START=97

start() {
	[ -c /dev/watchdog ] || return 1
	[ -x /sbin/watchdog ] || return 1
	/bin/nice -n 0 /sbin/watchdog -t 5 /dev/watchdog
}
stop() {
	killall watchdog
}
